server:
  port: 6060
  
spring:
  mvc:
    view:
      prefix: /view/
      suffix: .jsp
      
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: ranjith
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
